/**
 * だれトーク 配色プレビュー（10案）
 * 配色定義（採用中は CURRENT_PALETTE / theme.js）
 */
export const CURRENT_PALETTE = {
  id: 'jobs-lavender-dawn',
  name: 'ラベンダードーン（採用中）',
  by: 'チーム多数決',
  reason: '落ち着きを保ちつつ背景を明るく。ブランド紫を維持。',
  bg: '#f0edff',
  card: '#ffffff',
  primary: '#6c5ce7',
  primaryText: '#ffffff',
  text: '#1f1a33',
  textMuted: '#5e5678',
  border: '#ddd6f5',
  tag: '採用中',
};

export const COLOR_PALETTES = [
  {
    id: 'jobs-lavender-dawn',
    name: 'ラベンダードーン',
    by: 'ジョブズ（統括）',
    reason:
      '落ち着きを保ちつつ背景を明るく。ブランド紫を維持し、初回リリースの「安心・話しやすさ」のバランス型。',
    youth: 'Z世代に人気のラベンダー系。夜でも重くなりにくい。',
    bg: '#f0edff',
    card: '#ffffff',
    primary: '#6c5ce7',
    primaryText: '#ffffff',
    text: '#1f1a33',
    textMuted: '#5e5678',
    border: '#ddd6f5',
    tag: 'チーム提出',
  },
  {
    id: 'haruka-coral-mist',
    name: 'コーラルミスト',
    by: 'はるか（リサーチ）',
    reason:
      '短尺動画・SNSで見かけるコーラル×ラベンダーの組み合わせ。若者に「今っぽい」と感じられやすい。',
    youth: 'TikTok・Instagramで流行のソフトコーラル・くすみピンク系。',
    bg: '#fff5f2',
    card: '#ffffff',
    primary: '#e8788a',
    primaryText: '#ffffff',
    text: '#2a1f22',
    textMuted: '#7a5f66',
    border: '#f5ddd8',
    tag: 'チーム提出',
  },
  {
    id: 'kazama-morning-sky',
    name: 'モーニングスカイ',
    by: '風間（冒頭構成）',
    reason:
      '起動直後の第一印象を明るく。空のような青で「新しい会話が始まる」感じを出す。',
    youth: '明るい空色は全年齢に好印象。10代は「軽い・話しやすい」印象を受けやすい。',
    bg: '#eef6ff',
    card: '#ffffff',
    primary: '#4a9eed',
    primaryText: '#ffffff',
    text: '#142033',
    textMuted: '#4d6278',
    border: '#d4e6f7',
    tag: 'チーム提出',
  },
  {
    id: 'takumi-clear-lavender',
    name: 'クリアラベンダー',
    by: '匠（ブラッシュアップ）',
    reason:
      '落ち着く色味のまま、文字とボタンのコントラストを上げて読みやすく。長時間見ても疲れにくい明るめUI。',
    youth: '落ち着き＋読みやすさは、学生でも大人でも選ばれやすい。',
    bg: '#f6f4fc',
    card: '#ffffff',
    primary: '#5b4fd1',
    primaryText: '#ffffff',
    text: '#1a1730',
    textMuted: '#555070',
    border: '#e0dcf0',
    tag: 'チーム提出',
  },
  {
    id: 'koto-peach-talk',
    name: 'ピーチトーク',
    by: 'こと（台本）',
    reason:
      '言葉どおり「話す」温かみを前面に。堅すぎず、やさしい第一印象で利用規約前の不安を和らげる。',
    youth: 'ピーチ・クリーム系は「フレンドリー」アプリで好まれやすい。',
    bg: '#fff8f0',
    card: '#ffffff',
    primary: '#f0924d',
    primaryText: '#ffffff',
    text: '#2a2018',
    textMuted: '#7a6555',
    border: '#f0e0d0',
    tag: 'チーム提出',
  },
  {
    id: 'mint-echo',
    name: 'ミントエコー',
    by: 'ブレスト候補 A',
    reason:
      '落ち着く・リラックスのイメージ。メンタルウェルネス系アプリで若者に支持されるミントグリーン。',
    youth: '「癒し」「深呼吸」系コンテンツと相性がよい色。',
    bg: '#eef9f4',
    card: '#ffffff',
    primary: '#3db88a',
    primaryText: '#ffffff',
    text: '#142820',
    textMuted: '#4d6b5c',
    border: '#d0ebe0',
    tag: '参考案',
  },
  {
    id: 'bubble-pop',
    name: 'バブルポップ',
    by: 'ブレスト候補 B',
    reason:
      '若者向けの明るさを意識。紫ピンクでだれトークの個性を保ちつつ、暗さを解消。',
    youth: 'ゲーム・配信アプリでよく見るポップな紫ピンク。',
    bg: '#faf0ff',
    card: '#ffffff',
    primary: '#b86ce8',
    primaryText: '#ffffff',
    text: '#241a2e',
    textMuted: '#6b5580',
    border: '#eadcf5',
    tag: '参考案',
  },
  {
    id: 'cloud-minimal',
    name: 'クラウドミニマル',
    by: 'ブレスト候補 C',
    reason:
      'ニュートラルで落ち着く。色に馴染みがなく、長く使っても飽きにくいミニマル路線。',
    youth: 'Threads・Discordのライト系UIに慣れた層に受け入れられやすい。',
    bg: '#f4f4f6',
    card: '#ffffff',
    primary: '#6366f1',
    primaryText: '#ffffff',
    text: '#18181b',
    textMuted: '#52525b',
    border: '#e4e4e7',
    tag: '参考案',
  },
  {
    id: 'ocean-voice',
    name: 'オーシャンボイス',
    by: 'ブレスト候補 D',
    reason:
      '声・通話の「清涼感」。海系の青緑は信頼と開放感のバランスがよい。',
    youth: '夏〜通年、爽やか系は全年齢で好印象。',
    bg: '#e8f7fa',
    card: '#ffffff',
    primary: '#2aabbf',
    primaryText: '#ffffff',
    text: '#0f2a30',
    textMuted: '#4a6d75',
    border: '#cce8ee',
    tag: '参考案',
  },
  {
    id: 'sunset-glow',
    name: 'サンセットグロウ',
    by: 'ブレスト候補 E',
    reason:
      '夕方のやわらかい光。暗くなりすぎず、エネルギーと落ち着きの中間。',
    youth: 'サンセットグラデ系は写真・SNSで人気のトーン（単色で落ち着きを維持）。',
    bg: '#fff4ec',
    card: '#ffffff',
    primary: '#e86b4a',
    primaryText: '#ffffff',
    text: '#2a1c14',
    textMuted: '#7a5e50',
    border: '#f5ddd0',
    tag: '参考案',
  },
];
